### PR TITLE
Increased mission start time, and fixed Tembelan weather issue

### PR DESCRIPTION
**Pull request by Qerbas**
To fully load in the prison consistently the sleep value has to be set to 12. It can load faster, but it depends on the prison.

Tembelan island also has an issue where the map would load as incredible foggy a significant portion of the time regardless of the weather parameters. Removing the "startFogBase=250;" from the mission.sqm fixes that issue.

### CODE REVIEW

**Comment by NeoArmageddon** [comment]
Please don't mix gameplay and fix pull request. Instead create a new local/private branch against the master branch an create a different line of commits for me to integrate.

Also 12 seconds sounds WAY too long. The problem first occured after I improved the loading time of escape, but it was never as long as 12 seconds. Even the 3s we have right now is too long in my opinion. Right now I consider the 12 seconds for loading an edge case that is not worth adressing.
Did you tested this on a dedicated server or locally?

**Comment by Qerbas** [comment]
Ok, sorry about that.  Since they were really minor gameplay tweaks I figured it would be fine, but I'll keep that in mind in the future.

I agree that 12 seconds is too long, but it was the only amount of time where the prison loaded in 100% reliably.  3 seconds only fully loaded in the prison a small percentage of the time and 8 seconds was about 60% of the time.  The original prison definitely takes the longest amount of time to load and almost always needs the full 12 seconds.  Another issue I noticed is that players can still move during that loading screen so there is a chance they can just run out of the prison while the sleep is running.  it would probably be a dumb idea and not really worth fixing, but just something I'd like to note.

I tested it on a dedicated server and the server is on a 1TB Mushkin Enhanced Reactor SSD and an i7-6700k overclocked to 4.6GHz with 16GB of 3466Mhz ram so my hardware shouldn't be the bottleneck.  I tested pipeline 124 from 2019-3-7 which is the most recent version without the new mission initialization and it fully loads the prison in about 4-5 seconds reliably.

**Comment by NeoArmageddon** [comment]
The problem is not the server hardware. This has nothing to do with performance but with network bandwidth and Armas netcode. You can simply test this by hosting with a client: The prison is instantly ready there and takes some time to broadcast to connected clients when over internet.
Also this is really just some cosmetic issue (or when a player is really impatience and runs off, but then he gets shot). Making players wait artificially long is a more pressing problem in my opinion than just a visual glitch that only persists a few seconds.

**Comment by Qerbas** [comment]
I agree, and I'd like to remove the wait time, however players running out isn't the primary concern.  I should've mentioned this in the first post, but I've had players spawn outside of the prison on occasion on the new system, and I've only played a handful of sessions with groups, so statistically I think this will become a major issue when released publicly.  Not only that, I usually only play with 4-5 players max, and haven't tested with large groups like 8 or 10, which will only magnify the issue even more.

If the prison can't be fully formed on start, then all of the other prisons aside from the default one will have to be removed or changed to be much larger to avoid this issue.

Is there any other way to bring the improvements of the new mission initialization, which in your words on the discord were, "To fix the problem with persistent servers that auto start missions without players, the bootstrap script is halting the servers initialization until atleast one player is present." while having the same loading experience as the older versions of escape?

**Comment by Qerbas** [comment]
I captured an example of spawning outside of the prison.  It happened when solo testing so it looks like it can still happen in those circumstances.  https://www.youtube.com/watch?v=nnInXXe9sYY

**Pull request closed without merging**
