### PR TITLE
Removing bad/bugged templates

### PR DESCRIPTION
**Pull request by Qerbas**
Unfortunately all of the templates added since 1.9 have critical issues with object spawning that have yet to be resolved, and in order to push out 1.10 faster I think they should just be removed from spawning until they can be fixed with the new system in a future release.  Also, a couple of the older templates have some issues and/or are not up to the quality of the other ones so I removed them too.  I'll put screenshots/videos below demonstrating the issues and explain my reasoning for removing them.

**Ammo Bases**
fn_AmmoDepot3
While this ammo depot has fairly consistent box spawns, the turrets are facing objects blocking their view, and the outside walls tend to clump up in odd ways
fn_AmmoDepot3

fn_AmmoDepot4
Ammo depot 4 has issues with boxes spawning underneath buildings and the turrets have ok views but are still rotated in odd ways.
fn_AmmoDepot4
fn_AmmoDepot4_1

fn_AmmoDepot5
This one has severe issues with boxes spawning not just underneath objects but clipping through other objects.  Turrets are also angled badly and are facing walls.  The pictures are from before the camonet removal but the spawning issues are still there.
fn_AmmoDepot5_2
fn_AmmoDepot5_3
fn_AmmoDepot5_1

**Comcenters**
fn_BuildComCenter4
Vehicles spawn so close to each other that they often clip into each other and explode.  Even when they don't they're difficult to drive off with.  One of the turrets also has a poor angle and is partially facing a wall.
fn_BuildComCenter4

fn_BuildComCenter5
Same issues as the previous comcenter
fn_BuildComCenter5

**Roadblocks**
fn_Roadblock
The vehicle often spawns in the middle of the road with no cover.  As a result AI vehicles will run into it possibly causing explosions.  fn_roadblock 3 looks very similar but has a better placed vehicle with some cover so this one is redundant.
fn_Roadblock

fn_Roadblock2
This one's not really buggy, but the turret has a poor angle since it's just aiming at the vehicle in front of it and the little barrier in the middle will cause more vehicle crashes and possibly explosions.  It's better to keep the road clear to prevent pileups.
fn_Roadblock2

fn_Roadblock4
The turrets/vehicles are placed in the middle of the road so they will get run into and they also have poor angles.  The base is also frequently misaligned with the road.
fn_Roadblock4

**Prisons**
fn_BuildPrison4
Prison guards will open the door and just walk into the base.  I have no idea why this happens but it is very frequent and only happens on this one and fn_BuildPrison5.  I have never seen this happen on any other templates in hundreds of sessions.  While it can be funny for seasoned players, new players might encounter this and just discard escape as another buggy mission and never play it it again.  First impressions are important and dying for no reason is the last thing new players want to experience.
https://www.youtube.com/watch?v=fiZ0r-u5tU8

fn_BuildPrison5
Same as other prison
https://www.youtube.com/watch?v=mbxuKVFscAc

### CODE REVIEW

**Comment by N0FG** [comment]
I've actually seen the guards walk into ALL of the prisons even going back as far as the original one in A2, Granted, they seem to like the wooden shacks more possibly because the doors are part of the model. Are guards not allowed in the prisons? I don't know of any prison IRL that doesn't have the guards surprising the inmates with a quick inspection of the cells. Personally, as soon as the alarm kicks off I'd like to see them actively assault all the prisons.

**Comment by Qerbas** [comment]
To be clear this behavior happens even when players have not picked up the weapons and have not been detected.  I haven't seen it on the other templates ever, or at least I can't recall a time where it has happened.

I don't think it's intended for the guards to enter the prison at all.  If it was an intended scripted behavior it might be interesting, but these aren't really prisons, just a makeshift holding zone.  The early escape is already difficult enough and it doesn't need to be made even harder.

**Comment by N0FG** [comment]
It;s not intended, but a bit of random realism shouldn't be seen as a bug either. I think the shack with the 2 doors is actually the best prison, probably for the same reasons you think it isn't. If you eventually see guards walk into all the prisons as I have, should they all get removed? Variety is the spice of life and sometimes  that variety is a kick to the balls, This is part of the attraction of Escape....sometimes it's nice to ya, sometimes it's a cnut. The regimentation of certain aspects of the mission is not always a positive approach. Why doesn't the early escape need to  be made even harder? Should it be made less harder? How about it just actually stays the way it is with a variation of difficulty with very few people complaining about it and if the odd new player is put off by that difficulty, then they can play one of the many other missions out there until their friends remind them Escape is one of, if not...the best.

**Comment by Qerbas** [comment]
Geez man you make it sound like I'm trying to ruin the mission, I'm just suggesting removing bugged bases.  There's still four other perfectly good prison cells.  I'm suggesting this change because there's a difference between *intended* randomness and just buggy randomness.  If the chance for guards walking in was consistent for all the bases it would be part of the mission but it isn't, and personally me and my group find that frustrating.

If you've seen the other bases exhibit this behavior go ahead and post a recording of it but I can all but guarantee you won't be able to because of how rare it is.  These two bases it happens around 1 out of 4 times, and the others maybe 1 out of a thousand times.

I've suggested and made many changes that have both decreased and increased the difficulty of the mission, and you can see that in the changelog.  I too love the variety and replayability of escape, which is why I spend so much time playing, editing, and testing it.

If you enjoy the bases, that's fine, you can always just maintain your own branch with them.  I've made some changes on my own personal branch that me and my group enjoys that Neo doesn't want in the official version of escape.

I'm suggesting these changes because I feel they're the best for the official version.  If Neo thinks the bugged behavior adds variety and won't be too much of a problem, that's fine.

**Comment by N0FG** [comment]
I can and do maintain my own branch, but if things get removed  then other ppl might not be able to do the same. The irony of you complaining about bugs in Arma is funny, but when it comes to the prison, that behaviour was seen when they were made and tested and I didn't consider it a bug. When AI walk into a building is it a bug, when you shoot at AI from a building and they don't walk in, is that a bug? It swings both ways, if you and your group don't like them, simply take them out, but don't make that decision for everybody. Also, I guarantee you wont see me post it, because it doesn't bother me, much like it wont bother me when other small buildings with doors get made into prisons and the guards randomly decide to walk in on occasion. You're just suggesting they get removed and I'm just suggesting they don't, but again, it's not my problem if your read between the lines and take it so personally.

**Comment by NeoArmageddon** [comment]
This discussion is kinda running in circles.
To clear things up: I don't mind the guards opening doors. It is caused by their random patrol routes. Not intended, but I think it is rare enough to not be super annoying.

Regarding this pull request: I want to keep them in for now. I am aware of the placement issues but until the new template spawning I won't mind some exploding vehicles. Happens with normal vehicles in road traffic aswell, so it is not something too special. I want to clear some templates up, which might fix them but also is a good preparation for the merge to the new system.

**Comment by Qerbas** [comment]
In regards to the prison doors, it's definitely more of a minor issue, but it does seem strange to me why they seem to walk into these *much* more frequently than the other four.  I don't know exactly how the AI works in Arma but I do know most games have some sort of navmesh system and maybe those objects have them so AI interact with them while the others don't, even though I think fn_BuildPrison1/fn_BuildPrison2/fn_BuildPrison3 are buildings and not constructed like fn_BuildPrison.  I might experiment with enabling 4/5 on my server and seeing how my players react, it has been a while since we've used them.

I hope the other base templates can be improved before 1.10 release, however.  Especially the ammo bases.  The comcenters and roadblocks aren't really critical (but I still think having half the bases destroyed/blocked by the vehicles inside is going to give a bad impression), but players not being able to get to the ammo boxes is going to be very frustrating and I can already see the comments complaining about them on the forums/Steam/discord etc.

**Pull request closed without merging**
