### PR TITLE
Vanilla Apex/US overhaul, Vanilla/US changes, CUP RU/SLA tweaks

### PR DESCRIPTION
**Pull request by Qerbas**
Been playing a lot of Vanilla recently and these have been in need of updates to bring them in line with my other unit config reworks.

Highlights of the Apex Rework: 
-Adjusted military/civilian traffic ratios to be more in line with my recent CUP reworks. 

-Added Snipers to infantry patrol types and adjusted infantry ratios accordingly, to prevent too many sniper spawns.  Also added CTRG units to recon units on Vanilla Apex US
This one is a bit experimental, but I've noticed that some versions have random snipers and others don't, and while it doesn't make a lot of sense to have them patrolling with regular squads, the units are already made up units that don't normally mix and and I think the gameplay variety they add outweighs the realism concerns.  In the future, maybe a separate class for sniper teams with slightly different AI behavior could be implemented.

-Changed Ammo depot to always spawn a vehicle with a turret
I noticed that vehicles at ammo depots with guns always spawn with a gunner so I think this might have always been intentional.  I think it adds a good bit of challenge to the mission and I kept it limited to MRAPs and armed cars so it won't be excessively challenging.

-Removed VTOL from extraction choppers since it is bugged at the moment.  
I was playing recently and I noticed that the VTOL won't take off after all players get in.  The mission will simply end normally after a given amount of time.  I just commented them out for now.

-Added many new weapons/weapon variants and adjusted gear and attachments units spawn to only use equipment they're supposed to
Besides the new weapons, which will always bring much needed variety, restricting the gear units spawn with (namely scopes) I think will help make each version feel unique.  CSAT units don't have the RCO, for example, so I removed all of those from the Vanilla/Vanilla Apex versions from everywhere except for the crash site.

Highlights of Vanilla
Same changes as above, but not as dramatic of a rework since I recently reworked Vanilla.  One thing different than the above is that I fixed the way too high ratio of Laws of war civilian vehicles.  I accidentally put many of them as `a3e_arr_Escape_MilitaryTraffic_CivilianVehicleClasses` instead of their appropriate ones, such as `a3e_arr_Escape_MilitaryTraffic_EnemyVehicleClasses_IND` but that has been resolved.  Also one of the `O_APC_Wheeled_02_rcws_F` was an old version that has some odd behavior so I replaced it with `O_APC_Wheeled_02_rcws_v2_F`

CUP RU/SLA
Only thing I did on these was I updated the civilian vehicles and removed some extraction helicopters.  I removed the unarmed helicopters to keep that in line with my other reworks, and also removed the Osprey since they're also bugged.  As soon as the extraction is triggered they seem to be destroyed since the extraction marker immediately turns into the red X with a circle, indicating a failed extraction.

### CODE REVIEW

**Comment by NeoArmageddon** [comment]
Sniper patrols should become a surprise (suggested by Scruffy)

**Comment by NeoArmageddon** [comment]
And non armed vehicles at ammo depots are meant to spawn.

**Comment by NeoArmageddon** [comment]
What is the problems with VTOL? Worked always fine when testing Apex.

**Comment by Qerbas** [comment]
Yeah for sniper teams that's what I meant by a separate class they'd be a fun surprise.  I feel like it would be difficult them to script them to bel, though.  If there's a way to spawn them at the tops of hills/and or buildings and be aware of players so they shoot at long range it'd be cool.  I think that's possible but not sure how effective it'll be in game.  Do you want me to remove the snipers from the pull request for now?

I'll add the unarmed vehicles back at the ammo base for now.  Easy enough to revert.  I might try the armed vehicles only on my server and see how it plays out.

The Yi-32 Xian has some seriously strange behavior.  I first noticed an issue when I was playing a normal session and the VTOLs didn't take off.  It happened again when playing another normal session.  

I gave it a further test on a dedicated server today, and both VTOLs will take off when playing solo.  However, if two or more players are playing and they both get in separate VTOLs either neither take off or just one, but never both.  If both get in one VTOL sometimes the one with players takes off and sometimes the one without players takes off but usually it's the one without players.  I tested with no mods on the server and client and the issue still occurs.  I captured a recording of the VTOL with players taking off and the other one not [here](https://www.youtube.com/watch?v=p1Ss3Pb2OVo) and  and one with the players in both VTOLs and one not taking off [here.](https://www.youtube.com/watch?v=jXsTaVINqBM)

The MV22 Osprey is a separate issue.  I think it might be a similar issue to the one in the past where scout planes in the IFA3 mod were spawning and just dropping to the ground.  That one is consistent too on a dedicated server.

**Pull request closed without merging**
