### PR TITLE
Merge improvements by kuroneko

### PR DESCRIPTION
**Pull request by NeoArmageddon**
I really like some of the improvements. Some where already on my list but I didn't found the time to go through the code and, for example, remove all A2 legacy "call compile".

The localisation is also something I wanted to do for a long time, which adds a nice new feature for non-english speaking players to the mission. For coherence I would move the strings to a STR_A3E_* namespace, if that is fine with @kuroneko

The changes to the templates are most likely obsolete with the new templating feature that comes Soon™.

### CODE REVIEW

**Comment by kuroneko** [comment]
Yup - feel free to shift the namespace.  I only put it in mine because I hadn't spoken to anybody about using theirs. :)

**Comment by NeoArmageddon** [comment]
Great. Generally you can use the A3E-tag for everything you directly add to the missions codebase. Do you plan to contribute further changes? If yes, we have a Discord for discussing this kind of stuff and also directly collecting feedback from players and server admins.

And I really appreciate your work here!

**Comment by kuroneko** [comment]
I'll join the discord at some point then - my work in that repo has largely been efforts to get my head around SQF and the arma3 engine's behaviours and quirks without starting on a new project from scratch (and to stop my own private dedicated server from complaining so much!).  I'm not finished with that branch, but it's not at a bad point to merge either.

**Comment by NeoArmageddon** [comment]
Sorry for the long delay. I should have merged this earlier!

**Pull request merged**
