### PR TITLE
Add configuring with CBA Settings

### PR DESCRIPTION
**Pull request by Dystopian**
When merged this pull request will:
- title;
- optimize some code in parameterInit.

CBA settings are better than mission parameters at least because they loads saved settings. And if you want to change 1 setting you don't have to set all other settings you usually set.

CBA Settings can be accessed on Briefing screen - `Configure addons` button or in Escape menu - Options - Addon options, choose `co10 Escape` "addon".  To activate Escape CBA settings check `Use CBA settings` checkbox. Also `Parameter Load and Save` mission parameter must be `Load previously saved settings` (this is default). If it has value of `Use settings below and save` or `Use settings below without saving` parameters work as usually.

All changes to settings work after mission restart.

This PR doesn't add CBA dependency to mission. Vanilla mission should work as usually.

### CODE REVIEW

**Comment by Dystopian** [comment]
tested, vanilla works correctly too

**Comment by Dystopian** [comment]
Very fast mission reconfiguring with CBA settings on dedicated server: configure on briefing (can do in game too), then `#restart`. Mission is loaded to briefing with new settings preserving all players slots.

**Comment by NeoArmageddon** [comment]
See Issue #75 . Some stuff from this PR will be integrated manually while working on the Escape specific dialog.

**Comment by NeoArmageddon** [comment]
How does this work in MP? My local CBA option menu just says "Options are overwritten by Server"? Is there an option missing to be able to remotely change the CBA setting son the server?

**Comment by Dystopian** [comment]
you must be an admin and go to `Server` tab not `Mission` and `Client`, see also https://github.com/CBATeam/CBA_A3/wiki/CBA-Settings-System

**Comment by NeoArmageddon** [comment]
Ah, perfect, I missed the server tab.

**Pull request merged**
